# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: JS Unit Tests

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/js/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/tests-js.yml'
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/js/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/tests-js.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-js:
    name: Jest unit tests
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Run JS unit tests
        run: npm run test:unit:js
